app/blueprints/blog/models.py
from. import bp as app
from app import db, login_manager
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True)
    username = db.Column(db.String(50), unique=True)
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    password = db.Column(db.String(200))

    def hash_my_password(self, password):
        self.password = generate_password_hash(password)

    def check_my_password(self,password):
        return check_password_hash(self.password, password)
    


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(250), nullable=False)
    body = db.Column(db.String(2500), nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user = db.relationship('User', backref='post')

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

# def hash_passwords():
#     users = User.query.filter(User.id < 6).all()
#     for user in users:
#         user.hash_my_password(user.password)
#         db.session.add(user)

#     db.session.commit()

app/blueprints/main/models.py
from. import bp as app

app/models.py
from app import db
from datetime import datetime

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True)
    username = db.Column(db.String(50), unique=True)
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    password = db.Column(db.String(200))

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(250), nullable=False)
    body = db.Column(db.String(2500), nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

app/__init__.py
from flask import Flask, flash, redirect, url_for
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

def create_app():

    app = Flask (__name__)

    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    # from app import routes, models
    from app.blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.blueprints.blog import bp as blog_bp
    app.register_blueprint(blog_bp)

    from app.blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    login_manager.login_view='auth.login'
    login_manager.login_message = 'You are not allowed to access this page'
    login_manager.login_message_category = 'danger'

    return app

app/blueprints/blog/__init__.py
from flask import Blueprint

bp = Blueprint('blog',__name__, url_prefix='/blog' )

from.import routes, models

app/blueprints/blog/routes.py
from.import bp as app
from app import  db
from flask import render_template, request,redirect, url_for, flash
from app.blueprints.blog.models import Post
from.models import Post
from flask_login import current_user, login_required



@app.route('/posts')
@login_required
def posts():
    all_posts =Post.query.all()
    return render_template('posts.html', posts=all_posts)

#Create a dynamic route that allos us
#to get a singple post, based on it's id

@app.route('/post/<id>')
@login_required
def post_by_id(id):
    post = Post.query.get(int(id))
    return render_template('post-single.html', post=post)

@app.route('/create-post', methods=["POST"])
@login_required
def create_post():
    title = request.form['inputTitle']
    body = request.form['inputBody']
    new_post = Post(title=title, body=body, user_id=current_user.id)
    db.session.add(new_post)
    db.session.commit()
    flash('Post created successfully', 'success')
    # flash('This is an error','danger')
    return redirect(url_for('blog.posts'))

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main',__name__, url_prefix='/' )

from.import routes, models

app/blueprints/main/routes.py
from. import bp as app
from flask import render_template
from flask_login import current_user

@app.route('/')
def home():
    return render_template('home.html', user=current_user)

@app.route('/about')
def about():
    return render_template('about.html')

app/templates/0_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} | Fakebook</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark mb-5">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Fakebook</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('blog.posts') }}">Posts</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        {% if current_user.is_anonymous %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            <div class=flashes>
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %}
        {% block content%}{% endblock content %}
    </main>

    <footer>
        This is a footer
    </footer>  
</body>
</html>

app/templates/1_profile.html.j2
<h1> User: {{ name }}</h1>
<h2>User Info:</h2>
<ul>
    <li>User Id: {{ user_id }}</li>
    <li>email: {{ email }}</li>
    <li>favfood: {{ favfood }}</li>
    <li>active: {{ is_active }}</li>
</ul>
{% if is_active %}
    <h2>Reviews:</h2> 
    {% for review in reviews %}
    <div>
        {{ review }}
    </div>
    {% endfor%}
{% else %}
    <h2>no reviews for inactive users</h2>
{% endif %}

app/templates/2_profile.html.j2
<h1> Car: {{ name }}</h1>
<h2>Car Info:</h2>
<ul>
    <li>year: {{ year }}</li>
    <li>price: {{ selling_price }}</li>
</ul>

app/templates/about.html
{% extends './0_layout.html' %}

{% block title %}About{% endblock title %}

{% block content %}
<h1>About</h1>
<p>This is the about page</p>
{% endblock content %}
    

app/templates/cars.html
{% for id, car in car_data.items() %}
<div>
    <p>Car ID: {{ 'id' }}</p>
    <h2>{{car['name']}}</h2>
    <p>year:{{car['year']}}</p>
    <p>selling price:{{car['selling_price']}} </p>
</div>
<hr>
{% endfor %}

app/templates/cars2.html.j2
# if you dont want to spread it out

{% for id, car in car_data.items()%}

<h1>current cars: {{id}}</h1>
<p>{{car['name']}}</p>

{% endfor %}

app/templates/home.html
{% extends './0_layout.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<h1>Home</h1>
{% if user.is_authenticated%}
<p>Welcome to our app {{ user.username }}</p>
{% else %}
<p>Please <a href="{{ url_for('auth.login') }}">Login</a></p>
{% endif %}
{% endblock content %}
    

app/templates/login.html
{% extends './0_layout.html' %}

{% block title %}Login{% endblock title %}

{% block content %}
<h1>Login</h1>

<form action="{{ url_for('auth.login') }}" method="POST">
    <input type="hidden" name="next" value="{{ request.args.get('next', '') }}">
    <div class="mb-3">
        <label for="email" class="form-label">Email address</label>
        <input type="email" class="form-control" id="email" name ="email" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>


{% endblock content %}

app/templates/post-single.html
{% extends './0_layout.html' %}

{% block title %}{{post.title}}{% endblock title %}

{% block content %}
<h1>{{post.title}}</h1>
<p>{{post.body}}</p>

{% endblock content %}

app/templates/posts.html
{% extends './0_layout.html' %}

{% block title %}Posts{% endblock title %}

{% block content %}
<h1>Posts</h1>
<form action="{{ url_for('blog.create_post') }}" method="POST">
    <div class="mb-3">
        <label for="inputTitle" class="form-label">Title</label>
        <input type="text" class="form-control" id="inputTitle" name="inputTitle">

    </div>
    <div class="mb-3">
        <label for="inputBody" class="form-label">Body</label>
        <input type="text" class="form-control" id="inputBody" name="inputBody">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% for post in posts %}
<div class="card">
    <div class="card-title" >
        <h2 ><a href="{{url_for('blog.post_by_id', id= post.id) }}">{{post.title }}</a></h2>   
    </div> 
    <div class="card-body">
        <p>{{ post.body }}</p>
        This post brought to you by: {{post.user.first_name}} {{post.user.last_name}}
    </div>

</div>
{% endfor %}
{% endblock content %}

app/templates/register.html
{% extends './0_layout.html' %}

{% block title %}Register{% endblock title %}

{% block content %}
<h1>Register</h1>

<form action="{{ url_for('auth.register') }}" method="POST">
    <div class="mb-3">
        <label for="email" class="form-label">Email address</label>
        <input type="email" class="form-control" id="email" name ="email" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password">
    </div>
    <div class="mb-3">
        <label for="confirmPassword" class="form-label">Confirm Password</label>
        <input type="password" class="form-control" id="confirmPassword" name="confirmPassword">
    </div>
    <div class="mb-3">
        <label for="username" class="form-label">username</label>
        <input type="text" class="form-control" id="username" name="username">
    </div>
    <div class="mb-3">
        <label for="firstName" class="form-label">First Name</label>
        <input type="text" class="form-control" id="firstName" name="firstName">
    </div>
        <label for="lastName" class="form-label">Last Name</label>
        <input type="text" class="form-control" id="lastName" name="lastName">
    </div>



    <button type="submit" class="btn btn-primary">Submit</button>
</form>


{% endblock content %}

app/templates/reset-password.html
{% extends './0_layout.html' %}

{% block title %}Reset Password{% endblock title %}

{% block content %}
<h1>Reset Password</h1>
<form action="{{ url_for('auth.reset_password') }}" method="POST">
    <div class="mb-3">
        <label for="oldPassword" class="form-label">Old Password</label>
        <input type="password" class="form-control" id="oldPassword" name ="oldPassword"> 

    </div>
    <div class="mb-3">
        <label for="newPassword" class="form-label">New Password</label>
        <input type="password" class="form-control" id="newPassword" name="newPassword">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>


{% endblock content %}